### ISSUE TITLE
Login the extension not successfully

### ISSUE THREAD

**Issue by Resulte** [casdoor/casdoor-chrome-extension#4]
I run the latest original code in localhost, but it's not successful for login. @wenxuan70 

https://user-images.githubusercontent.com/34178764/183902927-71ad4c4a-1409-49fc-b6b3-7dea9675bc64.mov

**Comment by hsluoyz** [comment]
@wenxuan70 ptal

**Comment by wenxuan70** [comment]
Hi @Resulte!
Can you post the configuration of your manifest.json file?
